### PR TITLE
feat(feat(repository): adds support to identify entity ids automaticallyrepository): adds support to identify entity ids automatically

### LINKED ISSUE #35: ID field: use ID metadata from entity
With the upcoming release of the "ID field" feature (https://github.com/herbsjs/gotu/issues/46), it would be possible to read the entity's metadata and, as a convention, use those IDs that today need to be explicitly defined.  

```js
class ItemRepository extends Repository {
    constructor() {
        super({
            entity: Item,
            table: 'aTable',
            ids: ['id'],              // <---- not necessary
            knex: connection
        })
    }
```

Explicitly defining IDs would still be possible, but not mandatory for entities with IDs.

### PR DESCRIPTION
**Pull request by euduardo**
added support to identify entity ids automatically

fix #35

Update buchu package version, so now it uses the new `id` custom field to automatically identify the entities ids in the repository. It solves the issue #35 

## Proposed Changes

1. Created the private method `getEntityIds` in the `Repository` class. It automatically identify the ids of an entity and uses them if the user don't provide the `ids` option.
2. Created the unit tests for the constructor of `Repository`. It ensures the fields are filled the right way.
3. Updated the unit and integration tests to use the `id` custom field and the new feature, that allow omitting the `ids` in the repository constructor options

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request
- [x] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by dalssoft — APPROVED** [review]
good to go!

@jhomarolo any thoughts?

**Comment by jhomarolo** [comment]
@dalssoft I'm resolving the CI with @euduardo , but is good to go here

**Comment by dalssoft** [comment]
@jhomarolo feel free to merge when you finish with the CI

**Pull request merged**
